#!/usr/bin/env python3
import os, sys

NAME = "albumart-dl"

_srcdir = '%s/NAME/' % os.path.dirname(os.path.realpath(__file__))
_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    import albumart_dl
    if __name__ == '__main__':
        NAME.main(repo_path=_filepath)
else: # Python 2
    print("[fatal] Python 3 is required!")
    print("try to run this script using 'python3 {}'.".format("albumart-dl"))
